//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectStore.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class CollectionTable
    {
        [Key]
        [Display(Name = "Id")]
        public int Id { get; set; }
        [Display(Name = "Title")]
        [Required(ErrorMessage = "This field is required.", AllowEmptyStrings = false)]
        public string Title { get; set; }
        [Display(Name = "Author")]
        public string Author { get; set; }
        [Display(Name = "Director")]
        public string Director { get; set; }
        [Display(Name = "DateReleased")]
        public Nullable<System.DateTime> DateReleased { get; set; }
        [Display(Name = "Price")]
        [Required(ErrorMessage = "This field is required.", AllowEmptyStrings = false)]
        [Range(0.01, 999.99, ErrorMessage = "Price is out of range.")]
        public double Price { get; set; }
        [Display(Name = "Type")]
        [Required(ErrorMessage = "This field is required.", AllowEmptyStrings = false)]
        [RegularExpression("Book|Movie", ErrorMessage = "This field should be \"Book\" or \"Movie\"")]
        public string Type { get; set; }
    }
}
